### ISSUE TITLE
Midi input says "No response"

### ISSUE THREAD

**Issue by RyanKick** [strymon/spl#10]
Whenever i try to set up my Timeline to connect to the Strymon Librarian, i keep getting a no response error. Any idea how to fix it

**Comment by luntar** [comment]
Hi Ryan,
Thanks for the issue report.

I recommend contacting Hugo and Matt directly at support@strymon.net
To help you fix this issue, we will need more information about your computer setup, etc... 
Hugo or Matt will help you with the details.

Also, take a look at this:

> 
> Problems like this typically arise when using plug-and-play type MIDI interfaces, or if you do not have the latest drivers for your computer's specific operating system version installed for your MIDI interface.
> 
> What is the make and model of your MIDI interface?  Does it require software drivers to work with your computer?  If so, please ensure that these are installed.
> 
> If this does not help with the connection, the MIDI interface you have may not be robust enough to handle the data transfer between our pedals and the computer. We recommend using a different MIDI interface with dedicated software drivers that are compatible with your computer's specific operating system version.
> 
> We recommend using a dedicated MIDI interfaces with developed drivers for your computer’s specific operating system version such as the Roland UM-ONE or the Yamaha UX-16.
> 
> Also, make sure that your connections are correct: MIDI IN cable to MIDI OUT port on the pedal and MIDI OUT cable to MIDI IN port on the pedal.  Some MIDI interfaces have cable ends that tell you where to connect them ('TO MIDI IN' connects to 'MIDI IN' port and 'TO MIDI OUT' connects to 'MIDI OUT' port, for example).

**Comment by luntar** [comment]
Hi Ryan, hope you had luck getting this working.  I'm closing this issue but if you need more help please give us a call or email.
