### ISSUE TITLE
Preset Editor

### ISSUE THREAD

**Issue by shshaw** [strymon/spl#4]
Any plans to expand this tool to allow for editing of presets? 

Looks like there's an independent dev out there working on this, and he may have had some collaboration with you guys: http://www.thegearpage.net/board/showthread.php?t=1394462

I would love to see:
* **A GUI to tweak parameters.** Make some of those "deep" menu options easier to adjust
* **The ability to tweak options on the fly** Play around with a sound without having to bend over and mess with menus

**Comment by luntar** [comment]
Great ideas!
But nothing officially planned.  Leaving this open...

**Comment by aaronedmiston** [comment]
I know it's been quite a while since this "issue" has been opened, but have there been any plans set in place to allow for this? I would pay for an editor as described in the initial question.

**Comment by luntar** [comment]
Hi, thanks for the comment! 
Yes, things are in motion and we are planning on announcing something soon.

@aaronedmiston, @shshaw - If you are interested in testing a pre-release version, send me an email (johnb@strymon.net) and I will send you a link.   Any comments and testing feedback would be much appreciated.

-John

**Comment by aaronedmiston** [comment]
Is the pre-release Mac-compatible?

**Comment by luntar** [comment]
Yes, the pre-release supports OSX and Windows.

**Comment by aaronedmiston** [comment]
Awesome, request sent!

**Comment by luntar** [comment]
Got it.  Running some tests on the latest build.  I'll send you a link shortly.
Thanks again!

**Comment by luntar** [comment]
Closing this issue as we have released a tool that can both edit and organize presets.

The tool is called Nixie.  Here's some links:

[Blog post] (http://strymon.net/nixie-public-beta/)
[Nixie Download Page] (http://strymon.net/support/nixie)

<img width="460" alt="timeline cap" src="https://cloud.githubusercontent.com/assets/253440/17573231/e64160f0-5f0d-11e6-90da-01f92e8d8a37.PNG">

**Comment by shshaw** [comment]
Awesome 👍 Sorry I couldn't test the beta, but I'm looking forward to
trying it out!
