### ISSUE TITLE
Device Rejected Write Command

### ISSUE THREAD

**Issue by gsiefert** [strymon/spl#5]
When renaming a preset and attempting to Sync, I get the error "Device Rejected Write Command". Using Strymon Timeline and the TimeLine reports "Error" on its display.

Using Windows 8.

![image](https://cloud.githubusercontent.com/assets/662999/4500786/7fedc250-4a9a-11e4-9101-b811c388c369.png)

**Comment by luntar** [comment]
Librarian pre-release 0.9.4.1 or better has code in place that should prevent this error, or at least do a better job or recovering from such issues and allowing a clean sync.

### Some Details
This issues has been reproduced using several different USB MIDI devices.  In my test case, a MIDI sysex message is delivered to a USB MIDI interface from a host test program.  The data payload was never delivered to the target or was corrupted before it was placed on the USB.  Using an bus analyzer, this pattern was confirmed.

My best guess is that this is an overflow issues - too much data too fast; some USB MIDI interfaces are better than others.

However, if an error or timeout is detected, throttling the MIDI data-out transfers can work around the issue.
